### ISSUE TITLE
Assume `LitModular` by default in configuration

### ISSUE THREAD

**Issue by dxoigmn** [IntelLabs/MART#190]
Right now our configuration is rather verbose when it comes to models:
```yaml
model:
  _target_: mart.models.LitModular
  _convert_: all
  output_preds_key: preds
  output_target_key: target
  modules:
    ...
  training_sequence:
    ...
  ...
```
We could clean this up by assuming `LitModular` by default and moving all keys under `model` up 1 level like:
```yaml
output_preds_key: preds
output_target_key: target
modules:
  ...
training_sequence:
  ...
...
```
