### ISSUE TITLE
Add support for extended transforms in Lambda and SplitLambda

### ISSUE THREAD

**Issue by dxoigmn** [IntelLabs/MART#51]
Right now it is not possible to use extended transforms with `Lambda` and `SplitLambda`. For example, it would be useful to do something like:
```yaml
_target_: mart.transforms.SplitLambda
lambd:
  _target_: mart.transforms.Compose
  transforms:
    - _target_: mart.transforms.RandomHorizontalFlip
split_size_or_sections: 3
lambd_section: -1
dim: 0
```

It would also be nice to support original torchvision transforms:
```yaml
_target_: mart.transforms.SplitLambda
lambd:
  _target_: mart.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Normalize
      mean: 0
      std: 255
split_size_or_sections: 3
lambd_section: -1
dim: 0
```
